# Generated by Django 2.0.6 on 2018-06-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='publication_date',
            new_name='pub_date',
        ),
    ]
